### ISSUE TITLE
Available in rendered form/github-pages?

### ISSUE THREAD

**Issue by blakehawkins** [stefwalter/slides-cyborg-teams#1]
Thanks a lot for the talk at FOSDEM. Looking to spread the word for my team.

Any chance you already have a rendered version of this?

**Comment by stefwalter** [comment]
Good point. I've updated the rendered version committed in this repo:

https://github.com/stefwalter/slides-cyborg-teams/raw/master/slides-cyborg-teams.pdf

**Comment by blakehawkins** [comment]
Thanks! :beers:
